jaji_hackthon_back/src/Entity/Soignant.php
<?php

namespace App\Entity;

use App\Repository\SoignantRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SoignantRepository::class)]
class Soignant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $doctolib_url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $num_national = null;

    #[ORM\ManyToOne(inversedBy: 'soignant')]
    private ?Formation $formation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDoctolibUrl(): ?string
    {
        return $this->doctolib_url;
    }

    public function setDoctolibUrl(?string $doctolib_url): self
    {
        $this->doctolib_url = $doctolib_url;

        return $this;
    }

    public function getNumNational(): ?string
    {
        return $this->num_national;
    }

    public function setNumNational(?string $num_national): self
    {
        $this->num_national = $num_national;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

jaji_hackthon_back/src/Form/SoignantType.php
<?php

namespace App\Form;

use App\Entity\Soignant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SoignantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('category')
            ->add('doctolib_url')
            ->add('num_national')
            ->add('formation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Soignant::class,
        ]);
    }
}

jaji_hackthon_back/src/Controller/SoignantController.php
<?php

namespace App\Controller;
use App\Entity\Soignant;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Asset\UrlPackage;
use Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api", name="api_")
 */

#[Route('/soignant')]
class SoignantController extends AbstractController
{
    #[Route('/', name: 'app_soignant_index', methods: ['GET'])]
    public function index(ManagerRegistry $doctrine): Response
    {
        $soignants = $doctrine
            ->getRepository(Soignant::class)
            ->findAll();

        $data = [];

        foreach ($soignants as $soignant) {
            $localPackage = new UrlPackage(
                ['http://localhost:8000/pictures/soignant', 'http://127.0.0.1:8000/pictures/soignant'],
                new EmptyVersionStrategy()
            );
            $link = '';
            if($soignant->getImage()) $link = $localPackage->getUrl($soignant->getImage());
            $data[] = [
                'id' => $soignant->getId(),
                'firstName' => $soignant->getFirstname(),
                'lastName' => $soignant->getLastname(),
                'catégorie' => $soignant->getCategory(),
                'doctolib' => $soignant->getDoctolibUrl(),
                'numero' => $soignant->getNumNational(),
                'image' => $link
            ];
        }


        return $this->json($data);
    }

    #[Route('/new', name: 'app_soignant_new', methods: ['POST'])]
    public function new(Request $request, ManagerRegistry $doctrine): Response
    {
        $entityManager = $doctrine->getManager();

        $soignant = new Soignant();
        $soignant->setFirstname($request->request->get('firstName'));
        $soignant->setLastname($request->request->get('lastName'));
        $soignant->setCategory($request->request->get('catégorie'));
        $soignant->setDoctolibUrl($request->request->get('url'));
        $soignant->setNumNational($request->request->get('numéro'));
        $entityManager->persist($soignant);
        $entityManager->flush();

        return $this->json('Created new soignant successfully with id ' . $soignant->getId());
    }

    #[Route('/{id}', name: 'app_soignant_show', methods: ['GET'])]
    public function show(ManagerRegistry $doctrine, int $id): Response
    {
        $soignant = $doctrine->getRepository(Soignant::class)->find($id);

        if (!$soignant) {

            return $this->json('No project found for id' . $id, 404);
        }

        $data =  [
            'id' => $soignant->getId(),
            'firstName' => $soignant->getFirstname(),
            'lastName' => $soignant->getLastname(),
            'catégorie' => $soignant->getCategory(),
            'doctolib' => $soignant->getDoctolibUrl(),
            'numero' => $soignant->getNumNational()
        ];

        return $this->json($data);
    }

    #[Route('/{id}/edit', name: 'app_soignant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Soignant $soignant, SoignantRepository $soignantRepository): Response
    {
        $form = $this->createForm(SoignantType::class, $soignant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $soignantRepository->save($soignant, true);

            return $this->redirectToRoute('app_soignant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('soignant/edit.html.twig', [
            'soignant' => $soignant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_soignant_delete', methods: ['POST'])]
    public function delete(Request $request, Soignant $soignant, SoignantRepository $soignantRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$soignant->getId(), $request->request->get('_token'))) {
            $soignantRepository->remove($soignant, true);
        }

        return $this->redirectToRoute('app_soignant_index', [], Response::HTTP_SEE_OTHER);
    }
}

jaji_hackthon_back/templates/soignant/_delete_form.html.twig
<form method="post" action="{{ path('app_soignant_delete', {'id': soignant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ soignant.id) }}">
    <button class="btn">Delete</button>
</form>

jaji_hackthon_back/templates/soignant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

jaji_hackthon_back/templates/soignant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Soignant{% endblock %}

{% block body %}
    <h1>Edit Soignant</h1>

    {{ include('soignant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_soignant_index') }}">back to list</a>

    {{ include('soignant/_delete_form.html.twig') }}
{% endblock %}

jaji_hackthon_back/templates/soignant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Soignant index{% endblock %}

{% block body %}
    <h1>Soignant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Category</th>
                <th>Doctolib_url</th>
                <th>Num_national</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for soignant in soignants %}
            <tr>
                <td>{{ soignant.id }}</td>
                <td>{{ soignant.firstname }}</td>
                <td>{{ soignant.lastname }}</td>
                <td>{{ soignant.category }}</td>
                <td>{{ soignant.doctolibUrl }}</td>
                <td>{{ soignant.numNational }}</td>
                <td>
                    <a href="{{ path('app_soignant_show', {'id': soignant.id}) }}">show</a>
                    <a href="{{ path('app_soignant_edit', {'id': soignant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_soignant_new') }}">Create new</a>
{% endblock %}

jaji_hackthon_back/templates/soignant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Soignant{% endblock %}

{% block body %}
    <h1>Create new Soignant</h1>

    {{ include('soignant/_form.html.twig') }}

    <a href="{{ path('app_soignant_index') }}">back to list</a>
{% endblock %}

jaji_hackthon_back/templates/soignant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Soignant{% endblock %}

{% block body %}
    <h1>Soignant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ soignant.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ soignant.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ soignant.lastname }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ soignant.category }}</td>
            </tr>
            <tr>
                <th>Doctolib_url</th>
                <td>{{ soignant.doctolibUrl }}</td>
            </tr>
            <tr>
                <th>Num_national</th>
                <td>{{ soignant.numNational }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_soignant_index') }}">back to list</a>

    <a href="{{ path('app_soignant_edit', {'id': soignant.id}) }}">edit</a>

    {{ include('soignant/_delete_form.html.twig') }}
{% endblock %}